# bundle-install
# Autogenerated from man page /usr/share/man/man1/bundle-install.1.gz
complete -c bundle-install -l without -d 'A space-separated list of groups referencing gems to skip during installation'

