# cg_annotate
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cg_annotate.1.gz
complete -c cg_annotate -s h -l help -d 'Show the help message'
complete -c cg_annotate -l version -d 'Show the version number'
complete -c cg_annotate -l show -d 'Specifies which events to show (and the column order)'
complete -c cg_annotate -l sort -d 'Specifies the events upon which the sorting of the function-by-function entri…'
complete -c cg_annotate -l threshold -d 'Sets the threshold for the function-by-function summary'
complete -c cg_annotate -l show-percs -d 'When enabled, a percentage is printed next to all event counts'
complete -c cg_annotate -l auto -d 'When enabled, automatically annotates every file that is mentioned in the fun…'
complete -c cg_annotate -l context -d 'Print N lines of context before and after each annotated line'
complete -c cg_annotate -o 'I<dir>' -l include -d 'Adds a directory to the list in which to search for files'
complete -c cg_annotate -o I/--include -d 'options can be given to add multiple directories'

