# gtk4-builder-tool
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gtk4-builder-tool.1.gz
complete -c gtk4-builder-tool -l 3to4 -d 'is specified, simplify interprets the input as a GTK 3 ui file and attempts t…'
complete -c gtk4-builder-tool -l replace
complete -c gtk4-builder-tool -l id
complete -c gtk4-builder-tool -l css

