# gtk4-broadwayd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gtk4-broadwayd.1.gz
complete -c gtk4-broadwayd -l port -d 'Use PORT as the HTTP port, instead of the default 8080 + (DISPLAY - 1)'
complete -c gtk4-broadwayd -l address -d 'Use ADDRESS as the HTTP address, instead of the default http://127. 0. 0'
complete -c gtk4-broadwayd -l unixsocket -d 'Use ADDRESS as the unix domain socket address'

