# gtk4-launch
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gtk4-launch.1.gz
complete -c gtk4-launch -s '?' -l help -d 'Prints a short help text and exits'
complete -c gtk4-launch -l version -d 'Prints the program version and exits'

