# mt-st
# Autogenerated from man page /usr/lib/jvm/default/man/man1/mt-st.1.gz
complete -c mt-st -s h -d 'option.  The version of mt is printed with the'
complete -c mt-st -s v -d or
complete -c mt-st -l version -d option
complete -c mt-st -s f -d or
complete -c mt-st -s t -d option

