# scons
# Autogenerated from man page /usr/lib/jvm/default/man/man1/scons.1.gz
complete -c scons -s b -d 'Ignored for compatibility with non-GNU versions of make'
complete -c scons -s c -l clean -l remove -d 'Clean up by removing all target files for which a construction command is spe…'
complete -c scons -l cache-debug -d 'Print debug information about the CacheDir() derived-file caching to the spec…'
complete -c scons -l cache-disable -l no-cache -d 'Disable the derived-file caching specified by CacheDir()'
complete -c scons -l cache-force -l cache-populate -d 'When using CacheDir(), populate a cache by copying any already-existing, up-t…'
complete -c scons -l cache-readonly -d 'Use the cache (if enabled) for reading, but do not not update the cache with …'
complete -c scons -l cache-show -d 'When using CacheDir() and retrieving a derived file from the cache, show the …'
complete -c scons -l config -d 'This specifies how the Configure call should use or generate the results of c…'
complete -c scons -s C -l directory -d 'Change to the specified directory before searching for the SConstruct, Sconst…'
complete -c scons -s D -d 'Works exactly the same way as the \\*(T<-u\\*(T> option except for the way defa…'
complete -c scons -l debug -d 'Debug the build process.  type specifies the kind of debugging info to emit'
complete -c scons -l diskcheck -d 'Enable specific checks for whether or not there is a file on disk where the S…'
complete -c scons -l duplicate -d 'There are three ways to duplicate files in a build tree: hard links, soft (sy…'
complete -c scons -l enable-virtualenv -d 'Import virtualenv-related variables to SCons'
complete -c scons -s f -l file -l makefile -l sconstruct -d 'Use file as the initial SConscript file'
complete -c scons -s h -l help -d 'Print a local help message for this build, if one is defined in the SConscrip…'
complete -c scons -s H -l help-options -d 'Print the standard help message about command-line options and exit'
complete -c scons -s i -l ignore-errors -d 'Ignore all errors from commands executed to rebuild files'
complete -c scons -s I -l include-dir -d 'Specifies a directory to search for imported Python modules'
complete -c scons -l ignore-virtualenv -d 'Suppress importing virtualenv-related variables to SCons'
complete -c scons -l implicit-cache -d 'Cache implicit dependencies'
complete -c scons -l implicit-deps-changed -d 'Forces SCons to ignore the cached implicit dependencies'
complete -c scons -l implicit-deps-unchanged -d 'Force SCons to ignore changes in the implicit dependencies'
complete -c scons -l install-sandbox -d 'When using the \\*(T<Install\\*(T> functions, prepend path to the installation …'
complete -c scons -l interactive -d 'Starts SCons in interactive mode'
complete -c scons -s j -l jobs -d 'Specifies the number of jobs (commands) to run simultaneously'
complete -c scons -s k -l keep-going -d 'Continue as much as possible after an error'
complete -c scons -s m -d 'Ignored for compatibility with non-GNU versions of make'
complete -c scons -l max-drift -d 'Set the maximum expected drift in the modification time of files to SECONDS'
complete -c scons -l md5-chunksize -d 'Set the block size used to compute MD5 signatures to KILOBYTES'
complete -c scons -s n -l just-print -l dry-run -l recon -d 'No execute'
complete -c scons -l no-site-dir -d 'Prevents the automatic addition of the standard site_scons dirs to sys. path'
complete -c scons -l profile -d 'Run SCons under the Python profiler and save the results in the specified file'
complete -c scons -s q -l question -d 'Do not run any commands, or print anything'
complete -c scons -s Q -d 'Quiets SCons status messages about reading SConscript files, building targets…'
complete -c scons -l random -d 'Build dependencies in a random order'
complete -c scons -s s -l silent -l quiet -d 'Silent.  Do not print commands that are executed to rebuild target files'
complete -c scons -s S -l no-keep-going -l stop -d 'Ignored for compatibility with GNU make'
complete -c scons -l site-dir -d 'Uses the named dir as the site dir rather than the default site_scons dirs'
complete -c scons -l stack-size -d 'Set the size stack used to run threads to KILOBYTES'
complete -c scons -s t -l touch -d 'Ignored for compatibility with GNU make'
complete -c scons -l taskmastertrace -d 'Prints trace information to the specified file about how the internal Taskmas…'
complete -c scons -o tree -d 'Prints a tree of the dependencies after each top-level target is built'
complete -c scons -l tree -d 'Print the entire dependency tree after each top-level target is built'
complete -c scons -s u -l up -l search-up -d 'Walks up the directory structure until an SConstruct , Sconstruct , sconstruc…'
complete -c scons -s U -d 'Works exactly the same way as the \\*(T<-u\\*(T> option except for the way defa…'
complete -c scons -s v -l version -d 'Print the scons version, copyright information, list of authors, and any othe…'
complete -c scons -s w -l print-directory -d 'Print a message containing the working directory before and after other proce…'
complete -c scons -l no-print-directory -d 'Turn off -w, even if it was turned on implicitly'
complete -c scons -l warn -l warn -d 'Enable or disable warnings'
complete -c scons -l no-exec
complete -c scons -s Y -l repository -l srcdir -d 'Search the specified repository for any input and target files not found in t…'
complete -c scons -o arch
complete -c scons -o framework
complete -c scons -o frameworkdir
complete -c scons -o fmerge-all-constants
complete -c scons -o fopenmp
complete -c scons -o include
complete -c scons -o imacros
complete -c scons -o isysroot
complete -c scons -o isystem
complete -c scons -o iquote
complete -c scons -o idirafter
complete -c scons -s l
complete -c scons -s L
complete -c scons -o mno-cygwin
complete -c scons -o mwindows
complete -c scons -o openmp
complete -c scons -o pthread
complete -c scons -o std
complete -c scons -o Wa
complete -c scons -o Wl -o rpath
complete -c scons -s R
complete -c scons -o Wp
complete -c scons -o compatibility_version
complete -c scons -o current_version -d '$APPLELINK_NO_CURRENT_VERSION [scons(1)] and $SHLIBVERSION [scons(1)] to dete…'
complete -c scons -s 1 -d '(like the standard Python cmp function)'

