# sconsign
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sconsign.1.gz
complete -c sconsign -s a -l act -l action -d 'Prints the build action information for all entries or the specified entries'
complete -c sconsign -s c -l csig -d 'Prints the content signature (csig) information for all entries or the specif…'
complete -c sconsign -s d -l dir -d 'When the signatures are being read from a \\*(T<'
complete -c sconsign -s e -l entry -d 'Prints information about only the specified ENTRY'
complete -c sconsign -s f -l format -d 'The file(s) to be printed are in the specified FORMAT'
complete -c sconsign -s h -l help -d 'Prints a help message and exits'
complete -c sconsign -s i -l implicit -d 'Prints the list of cached implicit dependencies for all entries or for the sp…'
complete -c sconsign -l raw -d 'Prints a pretty-printed representation of the raw Python dictionary that hold…'
complete -c sconsign -s r -l readable -d 'Prints timestamps in a human-readable string, enclosed in single quotes'
complete -c sconsign -s t -l timestamp -d 'Prints the timestamp information for all entries or the specified entries'
complete -c sconsign -s v -l verbose -d 'Prints labels identifying each field being printed.  ENVIRONMENT'

