# stinit
# Autogenerated from man page /usr/lib/jvm/default/man/man8/stinit.8.gz
complete -c stinit -s f -d 'Specifies the name of the text file containing the definitions for different …'
complete -c stinit -s h -d 'Print the usage information'
complete -c stinit -s p -d 'The definition file is parsed but no tape drive initialization is attempted'
complete -c stinit -s r -d 'Rewind every device being initialized'
complete -c stinit -s v -d 'The more -v options (currently up to two), the more verbose output'
complete -c stinit -l version -d 'Print the program version'
complete -c stinit -o part

