# vgdb
# Autogenerated from man page /usr/lib/jvm/default/man/man1/vgdb.1.gz
complete -c vgdb -l pid -d 'Specifies the PID of the process to which vgdb must connect to'
complete -c vgdb -l vgdb-prefix -d 'Must be given to both Valgrind and vgdb if you want to change the default pre…'
complete -c vgdb -l wait -d 'Instructs vgdb to search for available Valgrind gdbservers for the specified …'
complete -c vgdb -l max-invoke-ms -d 'Gives the number of milliseconds after which vgdb will force the invocation o…'
complete -c vgdb -l cmd-time-out -d 'Instructs a standalone vgdb to exit if the Valgrind gdbserver it is connected…'
complete -c vgdb -l port -d 'Instructs vgdb to use tcp/ip and listen for GDB on the specified port nr rath…'
complete -c vgdb -s c -d 'To give more than one command to a standalone vgdb, separate the commands by …'
complete -c vgdb -s l -d 'Instructs a standalone vgdb to report the list of the Valgrind gdbserver proc…'
complete -c vgdb -s T -d 'Instructs vgdb to add timestamps to vgdb information messages'
complete -c vgdb -s D -d 'Instructs a standalone vgdb to show the state of the shared memory used by th…'
complete -c vgdb -s d -d 'Instructs vgdb to produce debugging output'

